name: Terraform Azure VM Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:



permissions:
  contents: read

jobs:
  deploy:
  
    env:
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}    

    
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: > 
        terraform init -backend=true -input=false
        -backend-config=subscription_id=${{ env.ARM_SUBSCRIPTION_ID}}
        -backend-config=resource_group_name="kopicloud-tfstate-rg"
        -backend-config=storage_accname="kopicloudiactest"
        -backend-config=container_name="core-tfstate"
        -backend-config=tenant_id=${{ env.ARM_TENANT_ID }}
        -backend-config=client_id=${{ env.ARM_CLIENT_ID }}
        -backend-config=client_secret=${{ env.ARM_CLIENT_SECRET }}
   
    - name: Terraform Plan
      run: terraform plan -input=false

    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false
